# Generated by Django 5.0.6 on 2024-05-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleKeywordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_name_uz", models.CharField(max_length=222)),
                ("key_name_en", models.CharField(max_length=222)),
            ],
            options={
                "verbose_name": "KeyWord",
                "db_table": "Keyword table",
            },
        ),
        migrations.CreateModel(
            name="ArticleSphereModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sphere_name_uz", models.CharField(max_length=222)),
                ("sphere_name_en", models.CharField(max_length=222)),
            ],
            options={
                "verbose_name": "ArticlSphereModel",
                "db_table": "Sphere table",
            },
        ),
    ]
