# Generated by Django 5.0.6 on 2024-05-17 06:02

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_app", "0001_initial"),
        ("journal_app", "0002_alter_journalmodel_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlespheremodel",
            options={"verbose_name": "ArticleSphereModel"},
        ),
        migrations.CreateModel(
            name="ArticleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_title_uz", models.CharField(max_length=333)),
                ("article_title_en", models.CharField(max_length=333)),
                ("article_desc_uz", models.CharField(max_length=333)),
                ("article_desc_en", models.CharField(max_length=333)),
                ("article_text_uz", ckeditor.fields.RichTextField()),
                ("article_text_en", ckeditor.fields.RichTextField()),
                ("article_references", models.CharField(max_length=333)),
                ("article_file", models.FileField(upload_to="article/")),
                ("article_date", models.DateTimeField(auto_now_add=True)),
                ("article_view_count", models.IntegerField(default=0)),
                (
                    "article_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "article_journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal_app.journalmodel",
                    ),
                ),
                (
                    "article_keywords",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article_app.articlekeywordmodel",
                    ),
                ),
                (
                    "article_sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article_app.articlespheremodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "db_table": "Article table",
                "ordering": ["-article_date"],
            },
        ),
        migrations.CreateModel(
            name="ArticleCommentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.CharField(max_length=222)),
                (
                    "comment_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article_app.articlemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "ArticleComment",
                "db_table": "ArticleComment table",
            },
        ),
    ]
