# Generated by Django 5.0.6 on 2024-05-16 18:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequirementsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_name_uz", models.CharField(max_length=333)),
                ("req_name_en", models.CharField(max_length=333)),
                ("part_text_uz", ckeditor.fields.RichTextField()),
                ("part_text_en", ckeditor.fields.RichTextField()),
            ],
            options={
                "verbose_name": "Requirements",
                "db_table": "Requirements table",
                "ordering": ["-id"],
            },
        ),
    ]
