# Generated by Django 5.0.6 on 2024-05-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requirement_faq_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requirementsmodel",
            old_name="part_text_en",
            new_name="req_text_en",
        ),
        migrations.RenameField(
            model_name="requirementsmodel",
            old_name="part_text_uz",
            new_name="req_text_uz",
        ),
    ]
